// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smsg/entity_msg.proto

package smsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "sanguosha.com/sgs_herox/proto/gameconf"
import gamedef "sanguosha.com/sgs_herox/proto/def"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllEnReqUserInfo_UserDataTyp int32

const (
	AllEnReqUserInfo_UDTInvalid AllEnReqUserInfo_UserDataTyp = 0
	AllEnReqUserInfo_UDTUser    AllEnReqUserInfo_UserDataTyp = 1
	AllEnReqUserInfo_UDTProp    AllEnReqUserInfo_UserDataTyp = 2
)

var AllEnReqUserInfo_UserDataTyp_name = map[int32]string{
	0: "UDTInvalid",
	1: "UDTUser",
	2: "UDTProp",
}
var AllEnReqUserInfo_UserDataTyp_value = map[string]int32{
	"UDTInvalid": 0,
	"UDTUser":    1,
	"UDTProp":    2,
}

func (x AllEnReqUserInfo_UserDataTyp) String() string {
	return proto.EnumName(AllEnReqUserInfo_UserDataTyp_name, int32(x))
}
func (AllEnReqUserInfo_UserDataTyp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{0, 0}
}

type AllEnRespUserInfo_ErrCode int32

const (
	AllEnRespUserInfo_Invalid      AllEnRespUserInfo_ErrCode = 0
	AllEnRespUserInfo_GetUserError AllEnRespUserInfo_ErrCode = 1
)

var AllEnRespUserInfo_ErrCode_name = map[int32]string{
	0: "Invalid",
	1: "GetUserError",
}
var AllEnRespUserInfo_ErrCode_value = map[string]int32{
	"Invalid":      0,
	"GetUserError": 1,
}

func (x AllEnRespUserInfo_ErrCode) String() string {
	return proto.EnumName(AllEnRespUserInfo_ErrCode_name, int32(x))
}
func (AllEnRespUserInfo_ErrCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

// 请求玩家信息
type AllEnReqUserInfo struct {
	Userid    uint64                         `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	DataTypes []AllEnReqUserInfo_UserDataTyp `protobuf:"varint,3,rep,packed,name=dataTypes,enum=smsg.AllEnReqUserInfo_UserDataTyp" json:"dataTypes,omitempty"`
}

func (m *AllEnReqUserInfo) Reset()                    { *m = AllEnReqUserInfo{} }
func (m *AllEnReqUserInfo) String() string            { return proto.CompactTextString(m) }
func (*AllEnReqUserInfo) ProtoMessage()               {}
func (*AllEnReqUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *AllEnReqUserInfo) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *AllEnReqUserInfo) GetDataTypes() []AllEnReqUserInfo_UserDataTyp {
	if m != nil {
		return m.DataTypes
	}
	return nil
}

type AllEnRespUserInfo struct {
	Seqid   int64                     `protobuf:"varint,1,opt,name=seqid" json:"seqid,omitempty"`
	Userid  uint64                    `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	ErrCode AllEnRespUserInfo_ErrCode `protobuf:"varint,3,opt,name=errCode,enum=smsg.AllEnRespUserInfo_ErrCode" json:"errCode,omitempty"`
	Data    *UserDataContent          `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *AllEnRespUserInfo) Reset()                    { *m = AllEnRespUserInfo{} }
func (m *AllEnRespUserInfo) String() string            { return proto.CompactTextString(m) }
func (*AllEnRespUserInfo) ProtoMessage()               {}
func (*AllEnRespUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *AllEnRespUserInfo) GetSeqid() int64 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

func (m *AllEnRespUserInfo) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *AllEnRespUserInfo) GetErrCode() AllEnRespUserInfo_ErrCode {
	if m != nil {
		return m.ErrCode
	}
	return AllEnRespUserInfo_Invalid
}

func (m *AllEnRespUserInfo) GetData() *UserDataContent {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserDataContent struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserDataContent) Reset()                    { *m = UserDataContent{} }
func (m *UserDataContent) String() string            { return proto.CompactTextString(m) }
func (*UserDataContent) ProtoMessage()               {}
func (*UserDataContent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *UserDataContent) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	UserBrief           *gamedef.UserBrief `protobuf:"bytes,1,opt,name=userBrief" json:"userBrief,omitempty"`
	IsOnline            bool               `protobuf:"varint,11,opt,name=isOnline" json:"isOnline,omitempty"`
	Status              int32              `protobuf:"varint,12,opt,name=status" json:"status,omitempty"`
	LoginIP             string             `protobuf:"bytes,15,opt,name=loginIP" json:"loginIP,omitempty"`
	ThirdAccountId      string             `protobuf:"bytes,16,opt,name=thirdAccountId" json:"thirdAccountId,omitempty"`
	CreateTime          int64              `protobuf:"varint,17,opt,name=createTime" json:"createTime,omitempty"`
	RegisterTime        int64              `protobuf:"varint,20,opt,name=registerTime" json:"registerTime,omitempty"`
	RegisterIP          string             `protobuf:"bytes,21,opt,name=registerIP" json:"registerIP,omitempty"`
	LoginTime           int64              `protobuf:"varint,22,opt,name=loginTime" json:"loginTime,omitempty"`
	LogoutTime          int64              `protobuf:"varint,24,opt,name=logoutTime" json:"logoutTime,omitempty"`
	BornTime            int64              `protobuf:"varint,25,opt,name=bornTime" json:"bornTime,omitempty"`
	ContinueLoginDayCnt int32              `protobuf:"varint,33,opt,name=continueLoginDayCnt" json:"continueLoginDayCnt,omitempty"`
	LoginDayCnt         int32              `protobuf:"varint,34,opt,name=loginDayCnt" json:"loginDayCnt,omitempty"`
	OnlineSec           int64              `protobuf:"varint,36,opt,name=onlineSec" json:"onlineSec,omitempty"`
	OnlineSecToday      int32              `protobuf:"varint,37,opt,name=onlineSecToday" json:"onlineSecToday,omitempty"`
	CardGroup           *gamedef.CardGroup `protobuf:"bytes,38,opt,name=cardGroup" json:"cardGroup,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *User) GetUserBrief() *gamedef.UserBrief {
	if m != nil {
		return m.UserBrief
	}
	return nil
}

func (m *User) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetLoginIP() string {
	if m != nil {
		return m.LoginIP
	}
	return ""
}

func (m *User) GetThirdAccountId() string {
	if m != nil {
		return m.ThirdAccountId
	}
	return ""
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetRegisterTime() int64 {
	if m != nil {
		return m.RegisterTime
	}
	return 0
}

func (m *User) GetRegisterIP() string {
	if m != nil {
		return m.RegisterIP
	}
	return ""
}

func (m *User) GetLoginTime() int64 {
	if m != nil {
		return m.LoginTime
	}
	return 0
}

func (m *User) GetLogoutTime() int64 {
	if m != nil {
		return m.LogoutTime
	}
	return 0
}

func (m *User) GetBornTime() int64 {
	if m != nil {
		return m.BornTime
	}
	return 0
}

func (m *User) GetContinueLoginDayCnt() int32 {
	if m != nil {
		return m.ContinueLoginDayCnt
	}
	return 0
}

func (m *User) GetLoginDayCnt() int32 {
	if m != nil {
		return m.LoginDayCnt
	}
	return 0
}

func (m *User) GetOnlineSec() int64 {
	if m != nil {
		return m.OnlineSec
	}
	return 0
}

func (m *User) GetOnlineSecToday() int32 {
	if m != nil {
		return m.OnlineSecToday
	}
	return 0
}

func (m *User) GetCardGroup() *gamedef.CardGroup {
	if m != nil {
		return m.CardGroup
	}
	return nil
}

func init() {
	proto.RegisterType((*AllEnReqUserInfo)(nil), "smsg.AllEnReqUserInfo")
	proto.RegisterType((*AllEnRespUserInfo)(nil), "smsg.AllEnRespUserInfo")
	proto.RegisterType((*UserDataContent)(nil), "smsg.UserDataContent")
	proto.RegisterType((*User)(nil), "smsg.User")
	proto.RegisterEnum("smsg.AllEnReqUserInfo_UserDataTyp", AllEnReqUserInfo_UserDataTyp_name, AllEnReqUserInfo_UserDataTyp_value)
	proto.RegisterEnum("smsg.AllEnRespUserInfo_ErrCode", AllEnRespUserInfo_ErrCode_name, AllEnRespUserInfo_ErrCode_value)
}

func init() { proto.RegisterFile("smsg/entity_msg.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xe1, 0x6e, 0xd3, 0x3c,
	0x14, 0xfd, 0xbc, 0x66, 0xeb, 0x7a, 0x3b, 0x75, 0x99, 0xbf, 0x6d, 0x32, 0x13, 0x1a, 0x21, 0x82,
	0x29, 0x08, 0x29, 0x1d, 0x45, 0x02, 0xf1, 0x8f, 0xd1, 0x4e, 0x53, 0x25, 0x24, 0x26, 0xd3, 0xfe,
	0x9e, 0xb2, 0xc4, 0x4d, 0x2d, 0xa5, 0x76, 0x67, 0x3b, 0x88, 0x3e, 0x10, 0xef, 0xc0, 0x6b, 0xf0,
	0x46, 0xc8, 0x4e, 0xdb, 0x74, 0x15, 0xf0, 0xa3, 0x92, 0xcf, 0xb9, 0xe7, 0x1e, 0x9f, 0x7b, 0xdd,
	0xc0, 0x89, 0x9e, 0xe9, 0xbc, 0xcb, 0x84, 0xe1, 0x66, 0x71, 0x37, 0xd3, 0x79, 0x3c, 0x57, 0xd2,
	0x48, 0xec, 0x59, 0xfa, 0xec, 0x9d, 0x4e, 0x44, 0x5e, 0x4a, 0x3d, 0x4d, 0xe2, 0x54, 0xce, 0xba,
	0x3a, 0xd7, 0x77, 0x53, 0xa6, 0xe4, 0xf7, 0xae, 0x13, 0x75, 0xf3, 0x64, 0xc6, 0x52, 0x29, 0x26,
	0xee, 0x70, 0x67, 0x16, 0x73, 0x56, 0x75, 0x9f, 0xbd, 0xfe, 0x77, 0x5f, 0xc6, 0x26, 0xf6, 0x57,
	0x89, 0xc3, 0x1f, 0x08, 0xfc, 0xab, 0xa2, 0xb8, 0x16, 0x94, 0x3d, 0x8c, 0x35, 0x53, 0x43, 0x31,
	0x91, 0xf8, 0x14, 0xf6, 0x4a, 0xcd, 0x14, 0xcf, 0xc8, 0x4e, 0x80, 0x22, 0x8f, 0x2e, 0x11, 0xfe,
	0x08, 0xad, 0x2c, 0x31, 0xc9, 0x68, 0x31, 0x67, 0x9a, 0x34, 0x82, 0x46, 0xd4, 0xe9, 0x85, 0xb1,
	0xcd, 0x1a, 0x6f, 0x5b, 0xc4, 0xf6, 0x30, 0xa8, 0xb4, 0xb4, 0x6e, 0x0a, 0xdf, 0x43, 0x7b, 0xa3,
	0x82, 0x3b, 0x00, 0xe3, 0xc1, 0x68, 0x28, 0xbe, 0x25, 0x05, 0xcf, 0xfc, 0xff, 0x70, 0x1b, 0x9a,
	0xe3, 0xc1, 0xc8, 0x2a, 0x7c, 0xb4, 0x04, 0xb7, 0x4a, 0xce, 0xfd, 0x9d, 0xf0, 0x17, 0x82, 0xa3,
	0xe5, 0x25, 0x7a, 0xbe, 0x0e, 0x7a, 0x0c, 0xbb, 0x9a, 0x3d, 0xf0, 0x8c, 0xa0, 0x00, 0x45, 0x0d,
	0x5a, 0x81, 0xbf, 0xc6, 0xff, 0x00, 0x4d, 0xa6, 0x54, 0x5f, 0x66, 0x8c, 0x34, 0x02, 0x14, 0x75,
	0x7a, 0xcf, 0x1e, 0x85, 0xaf, 0x7d, 0xe3, 0xeb, 0x4a, 0x46, 0x57, 0x7a, 0xfc, 0x0a, 0x3c, 0x3b,
	0x04, 0xf1, 0x02, 0x14, 0xb5, 0x7b, 0x27, 0x55, 0xdf, 0x6a, 0x92, 0xbe, 0x14, 0x86, 0x09, 0x43,
	0x9d, 0x24, 0x8c, 0xa0, 0xb9, 0x6c, 0xb7, 0x13, 0xd4, 0xb3, 0xf9, 0x70, 0x70, 0xc3, 0x8c, 0xed,
	0xb9, 0x56, 0x4a, 0x2a, 0x1f, 0x85, 0x6f, 0xe0, 0x70, 0xcb, 0x02, 0x9f, 0x83, 0x67, 0xc3, 0xba,
	0x79, 0xda, 0x3d, 0xa8, 0xef, 0xa1, 0x8e, 0x0f, 0x7f, 0x7a, 0xe0, 0x59, 0x88, 0x2f, 0xa1, 0x65,
	0x89, 0x4f, 0x8a, 0xb3, 0xc9, 0x52, 0x8d, 0x63, 0xfb, 0x4f, 0xb0, 0x4f, 0x3b, 0x5e, 0x55, 0x68,
	0x2d, 0xc2, 0x67, 0xb0, 0xcf, 0xf5, 0x17, 0x51, 0x70, 0xc1, 0x48, 0x3b, 0x40, 0xd1, 0x3e, 0x5d,
	0x63, 0xbb, 0x31, 0x6d, 0x12, 0x53, 0x6a, 0x72, 0x10, 0xa0, 0x68, 0x97, 0x2e, 0x11, 0x26, 0xd0,
	0x2c, 0x64, 0xce, 0xc5, 0xf0, 0x96, 0x1c, 0x06, 0x28, 0x6a, 0xd1, 0x15, 0xc4, 0x17, 0xd0, 0x31,
	0x53, 0xae, 0xb2, 0xab, 0x34, 0x95, 0xa5, 0x30, 0xc3, 0x8c, 0xf8, 0x4e, 0xb0, 0xc5, 0xe2, 0x73,
	0x80, 0x54, 0xb1, 0xc4, 0xb0, 0x11, 0x9f, 0x31, 0x72, 0xe4, 0x9e, 0x69, 0x83, 0xc1, 0x21, 0x1c,
	0x28, 0x96, 0x73, 0x6d, 0x98, 0x72, 0x8a, 0x63, 0xa7, 0x78, 0xc4, 0x59, 0x8f, 0x15, 0x1e, 0xde,
	0x92, 0x13, 0x77, 0xcf, 0x06, 0x83, 0x9f, 0x42, 0xcb, 0xc5, 0x72, 0x06, 0xa7, 0xce, 0xa0, 0x26,
	0x6c, 0x77, 0x21, 0x73, 0x59, 0x1a, 0x57, 0x26, 0x55, 0x82, 0x9a, 0xb1, 0x7b, 0xb9, 0x97, 0xaa,
	0x6a, 0x7e, 0xe2, 0xaa, 0x6b, 0x8c, 0x2f, 0xe1, 0xff, 0x54, 0x0a, 0xc3, 0x45, 0xc9, 0x3e, 0x5b,
	0xc3, 0x41, 0xb2, 0xe8, 0x0b, 0x43, 0x9e, 0xbb, 0x25, 0xfd, 0xa9, 0x84, 0x03, 0x68, 0x17, 0x1b,
	0xca, 0xd0, 0x29, 0x37, 0x29, 0x9b, 0x56, 0xba, 0xad, 0x7f, 0x65, 0x29, 0x79, 0x51, 0xa5, 0x5d,
	0x13, 0x76, 0xaf, 0x6b, 0x30, 0x92, 0x59, 0xb2, 0x20, 0x2f, 0x9d, 0xc5, 0x16, 0x6b, 0xdf, 0x3f,
	0x4d, 0x54, 0x76, 0xa3, 0x64, 0x39, 0x27, 0x17, 0x5b, 0xef, 0xdf, 0x5f, 0x55, 0x68, 0x2d, 0xba,
	0xdf, 0x73, 0x1f, 0xfc, 0xdb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x89, 0xf1, 0x70, 0x07, 0x74,
	0x04, 0x00, 0x00,
}
