# 是否为开发模式.
develop: true
# 运行模式 0 正常模式 1 白名单模式
runmode: 0
# 应用id
appid: 100
# 游戏分区号
game_area: 191

# mysql 配置, DSN 格式 user:password@tcp(localhost:3306)/db
db_game: "root:ZBJzbj123@tcp(localhost:3306)/sgs_herox?charset=utf8&parseTime=True&loc=Local"
#db_game: "root:zhubeijian@tcp(10.225.254.248:3306)/sgs_spy?charset=utf8&parseTime=True&loc=Local"
#db_game: "root:yk123456@tcp(127.0.0.1:3306)/sgs_herox?charset=utf8&parseTime=True&loc=Local"
db_account : ""
# 对应 netconfig 中 entity id.
# entity 按固定数目配置, 根据 userid hash 路由消息请求.
entity_nodes:
  - svrid: 501
    shard_cnt: 100
    chan_len: 5120
#  - svrid: 502
#    shard_cnt: 100
#    chan_len: 5120

# 敏感词过滤服务器地址, 如果配置为 "null", 则不进行过滤
#words_filter: "null"
words_filter: "http://filterword.sanguosha.com:50000/v1/query?"
#12 31
mq:
  public:
    type: "kafka"
    address: ["10.225.254.248:9092"]
    open: false

kafka:
  report:
    address: ["10.225.136.212:9092"]
    topic : "report"
    open: false
  log:
    address: [ "10.225.136.212:9092"]
    topic: "log_topic"
    open: false

redis:
  user:
    addr: 10.225.10.194:6379
    password: "Xu2009"
    max: 20
    max_idle: 10

  sgs_public:
    addr: 10.225.10.194:6379
    password: ""
    max: 20
    max_idle: 10

tablepark:
  url_auth: "http://47.98.156.154/api/user/userInfo"
  notice_open: true
  url_notice_gamestatus: "http://47.98.156.154/api/game/notice"
  url_notice_gamedata: "http://47.98.156.154/api/game/settleNotice"

# 游戏配置文件目录, 以 config.yaml 文件所在目录来相对配置.
game_config_path:
    base_config_path: "gameconf/game_base_config.json"
    stable_config_path: "gameconf/game_stable_config.json"

session_root: "../bin/web/data/filecache.txt"
web_root : ""