// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db/db.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db/db.proto

It has these top-level messages:
	CharInfo
	DBProp
	Score
	Int32KV
	Int64KV
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gamedef "sanguosha.com/sgs_herox/proto/def"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 角色其它信息
type CharInfo struct {
	// 玩家属性
	Icon     int32 `protobuf:"varint,1,opt,name=icon" json:"icon,omitempty"`
	IconEdge int32 `protobuf:"varint,2,opt,name=iconEdge" json:"iconEdge,omitempty"`
	// 统计数据
	OnlineSecToday int32 `protobuf:"varint,20,opt,name=onlineSecToday" json:"onlineSecToday,omitempty"`
	OnlineSecTotal int64 `protobuf:"varint,21,opt,name=onlineSecTotal" json:"onlineSecTotal,omitempty"`
	LoginDayCnt    int32 `protobuf:"varint,22,opt,name=loginDayCnt" json:"loginDayCnt,omitempty"`
	C11LoginDayCnt int32 `protobuf:"varint,23,opt,name=c11LoginDayCnt" json:"c11LoginDayCnt,omitempty"`
	LastLoginTime  int64 `protobuf:"varint,24,opt,name=lastLoginTime" json:"lastLoginTime,omitempty"`
	LastLogoutTime int64 `protobuf:"varint,25,opt,name=lastLogoutTime" json:"lastLogoutTime,omitempty"`
	LastResetTime  int64 `protobuf:"varint,30,opt,name=lastResetTime" json:"lastResetTime,omitempty"`
	Init           bool  `protobuf:"varint,51,opt,name=init" json:"init,omitempty"`
	// 当日胜负数据统计
	CurDayWinCountText   int32 `protobuf:"varint,60,opt,name=curDayWinCountText" json:"curDayWinCountText,omitempty"`
	CurDayLoseCountText  int32 `protobuf:"varint,61,opt,name=curDayLoseCountText" json:"curDayLoseCountText,omitempty"`
	CurDayWinCountVoice  int32 `protobuf:"varint,62,opt,name=curDayWinCountVoice" json:"curDayWinCountVoice,omitempty"`
	CurDayLoseCountVoice int32 `protobuf:"varint,63,opt,name=curDayLoseCountVoice" json:"curDayLoseCountVoice,omitempty"`
	// 总体胜负数据统计
	WinCountText   int32                `protobuf:"varint,100,opt,name=winCountText" json:"winCountText,omitempty"`
	LoseCountText  int32                `protobuf:"varint,101,opt,name=loseCountText" json:"loseCountText,omitempty"`
	WinCountVoice  int32                `protobuf:"varint,110,opt,name=winCountVoice" json:"winCountVoice,omitempty"`
	LoseCountVoice int32                `protobuf:"varint,111,opt,name=loseCountVoice" json:"loseCountVoice,omitempty"`
	Score          []*Score             `protobuf:"bytes,120,rep,name=score" json:"score,omitempty"`
	CardGroups     []*gamedef.CardGroup `protobuf:"bytes,121,rep,name=cardGroups" json:"cardGroups,omitempty"`
	NowUseId       int32                `protobuf:"varint,122,opt,name=nowUseId" json:"nowUseId,omitempty"`
}

func (m *CharInfo) Reset()                    { *m = CharInfo{} }
func (m *CharInfo) String() string            { return proto.CompactTextString(m) }
func (*CharInfo) ProtoMessage()               {}
func (*CharInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CharInfo) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *CharInfo) GetIconEdge() int32 {
	if m != nil {
		return m.IconEdge
	}
	return 0
}

func (m *CharInfo) GetOnlineSecToday() int32 {
	if m != nil {
		return m.OnlineSecToday
	}
	return 0
}

func (m *CharInfo) GetOnlineSecTotal() int64 {
	if m != nil {
		return m.OnlineSecTotal
	}
	return 0
}

func (m *CharInfo) GetLoginDayCnt() int32 {
	if m != nil {
		return m.LoginDayCnt
	}
	return 0
}

func (m *CharInfo) GetC11LoginDayCnt() int32 {
	if m != nil {
		return m.C11LoginDayCnt
	}
	return 0
}

func (m *CharInfo) GetLastLoginTime() int64 {
	if m != nil {
		return m.LastLoginTime
	}
	return 0
}

func (m *CharInfo) GetLastLogoutTime() int64 {
	if m != nil {
		return m.LastLogoutTime
	}
	return 0
}

func (m *CharInfo) GetLastResetTime() int64 {
	if m != nil {
		return m.LastResetTime
	}
	return 0
}

func (m *CharInfo) GetInit() bool {
	if m != nil {
		return m.Init
	}
	return false
}

func (m *CharInfo) GetCurDayWinCountText() int32 {
	if m != nil {
		return m.CurDayWinCountText
	}
	return 0
}

func (m *CharInfo) GetCurDayLoseCountText() int32 {
	if m != nil {
		return m.CurDayLoseCountText
	}
	return 0
}

func (m *CharInfo) GetCurDayWinCountVoice() int32 {
	if m != nil {
		return m.CurDayWinCountVoice
	}
	return 0
}

func (m *CharInfo) GetCurDayLoseCountVoice() int32 {
	if m != nil {
		return m.CurDayLoseCountVoice
	}
	return 0
}

func (m *CharInfo) GetWinCountText() int32 {
	if m != nil {
		return m.WinCountText
	}
	return 0
}

func (m *CharInfo) GetLoseCountText() int32 {
	if m != nil {
		return m.LoseCountText
	}
	return 0
}

func (m *CharInfo) GetWinCountVoice() int32 {
	if m != nil {
		return m.WinCountVoice
	}
	return 0
}

func (m *CharInfo) GetLoseCountVoice() int32 {
	if m != nil {
		return m.LoseCountVoice
	}
	return 0
}

func (m *CharInfo) GetScore() []*Score {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *CharInfo) GetCardGroups() []*gamedef.CardGroup {
	if m != nil {
		return m.CardGroups
	}
	return nil
}

func (m *CharInfo) GetNowUseId() int32 {
	if m != nil {
		return m.NowUseId
	}
	return 0
}

// 道具
type DBProp struct {
	Props    []*Int64KV `protobuf:"bytes,1,rep,name=props" json:"props,omitempty"`
	Consumes []*Int64KV `protobuf:"bytes,2,rep,name=consumes" json:"consumes,omitempty"`
}

func (m *DBProp) Reset()                    { *m = DBProp{} }
func (m *DBProp) String() string            { return proto.CompactTextString(m) }
func (*DBProp) ProtoMessage()               {}
func (*DBProp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DBProp) GetProps() []*Int64KV {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *DBProp) GetConsumes() []*Int64KV {
	if m != nil {
		return m.Consumes
	}
	return nil
}

// 隐藏分
type Score struct {
	ScoreType int32      `protobuf:"varint,1,opt,name=ScoreType" json:"ScoreType,omitempty"`
	Score     []*Int32KV `protobuf:"bytes,2,rep,name=score" json:"score,omitempty"`
}

func (m *Score) Reset()                    { *m = Score{} }
func (m *Score) String() string            { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()               {}
func (*Score) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Score) GetScoreType() int32 {
	if m != nil {
		return m.ScoreType
	}
	return 0
}

func (m *Score) GetScore() []*Int32KV {
	if m != nil {
		return m.Score
	}
	return nil
}

type Int32KV struct {
	Key int32 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	V   int32 `protobuf:"varint,2,opt,name=v" json:"v,omitempty"`
}

func (m *Int32KV) Reset()                    { *m = Int32KV{} }
func (m *Int32KV) String() string            { return proto.CompactTextString(m) }
func (*Int32KV) ProtoMessage()               {}
func (*Int32KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Int32KV) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Int32KV) GetV() int32 {
	if m != nil {
		return m.V
	}
	return 0
}

type Int64KV struct {
	Key int64 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	V   int64 `protobuf:"varint,2,opt,name=v" json:"v,omitempty"`
}

func (m *Int64KV) Reset()                    { *m = Int64KV{} }
func (m *Int64KV) String() string            { return proto.CompactTextString(m) }
func (*Int64KV) ProtoMessage()               {}
func (*Int64KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Int64KV) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Int64KV) GetV() int64 {
	if m != nil {
		return m.V
	}
	return 0
}

func init() {
	proto.RegisterType((*CharInfo)(nil), "db.CharInfo")
	proto.RegisterType((*DBProp)(nil), "db.DBProp")
	proto.RegisterType((*Score)(nil), "db.Score")
	proto.RegisterType((*Int32KV)(nil), "db.Int32KV")
	proto.RegisterType((*Int64KV)(nil), "db.Int64KV")
}

func init() { proto.RegisterFile("db/db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x5f, 0x8f, 0xd2, 0x40,
	0x14, 0xc5, 0xd3, 0x45, 0x90, 0xbd, 0xac, 0xc6, 0x8c, 0xab, 0x8e, 0x1b, 0xa3, 0x48, 0x8c, 0x62,
	0x4c, 0x8a, 0x0b, 0xc6, 0x27, 0xff, 0x24, 0x82, 0x51, 0xe2, 0x3e, 0x98, 0x2e, 0xae, 0x8f, 0xa6,
	0xb4, 0xb3, 0xd0, 0x08, 0x73, 0x9b, 0x4e, 0x0b, 0xd4, 0xef, 0xe4, 0x77, 0x34, 0x73, 0xa7, 0x40,
	0xa7, 0xf2, 0x40, 0x98, 0xfe, 0xce, 0xb9, 0xe7, 0xde, 0xb6, 0x33, 0x85, 0x56, 0x38, 0xed, 0x85,
	0x53, 0x37, 0x4e, 0x30, 0x45, 0x76, 0x14, 0x4e, 0xcf, 0x5e, 0x29, 0x5f, 0xce, 0x32, 0x54, 0x73,
	0xdf, 0x0d, 0x70, 0xd9, 0x53, 0x33, 0xf5, 0x6b, 0x2e, 0x12, 0xdc, 0xf4, 0xc8, 0xd2, 0x0b, 0xc5,
	0xb5, 0xfe, 0x99, 0x82, 0xce, 0xdf, 0x06, 0x34, 0x87, 0x73, 0x3f, 0x19, 0xcb, 0x6b, 0x64, 0x0c,
	0x6e, 0x44, 0x01, 0x4a, 0xee, 0xb4, 0x9d, 0x6e, 0xdd, 0xa3, 0x35, 0x3b, 0x83, 0xa6, 0xfe, 0xff,
	0x1c, 0xce, 0x04, 0x3f, 0x22, 0xbe, 0xbb, 0x66, 0xcf, 0xe1, 0x36, 0xca, 0x45, 0x24, 0xc5, 0xa5,
	0x08, 0x26, 0x18, 0xfa, 0x39, 0x3f, 0x25, 0x47, 0x85, 0x56, 0x7c, 0xa9, 0xbf, 0xe0, 0xf7, 0xda,
	0x4e, 0xb7, 0xe6, 0x55, 0x28, 0x6b, 0x43, 0x6b, 0x81, 0xb3, 0x48, 0x8e, 0xfc, 0x7c, 0x28, 0x53,
	0x7e, 0x9f, 0xc2, 0xca, 0x48, 0x27, 0x05, 0xe7, 0xe7, 0x17, 0x25, 0xd3, 0x03, 0xd3, 0xd1, 0xa6,
	0xec, 0x19, 0xdc, 0x5a, 0xf8, 0x2a, 0x25, 0x34, 0x89, 0x96, 0x82, 0x73, 0x6a, 0x68, 0x43, 0x9d,
	0x56, 0x00, 0xcc, 0x52, 0xb2, 0x3d, 0x34, 0x73, 0xd9, 0x74, 0x9b, 0xe6, 0x09, 0x25, 0x8c, 0xed,
	0xf1, 0x3e, 0x6d, 0x07, 0xe9, 0xe9, 0xc9, 0x28, 0xe5, 0x83, 0xb6, 0xd3, 0x6d, 0x7a, 0xb4, 0x66,
	0x2e, 0xb0, 0x20, 0x4b, 0x46, 0x7e, 0xfe, 0x33, 0x92, 0x43, 0xcc, 0x64, 0x3a, 0x11, 0x9b, 0x94,
	0xbf, 0xa3, 0x99, 0x0f, 0x28, 0xec, 0x35, 0xdc, 0x35, 0xf4, 0x02, 0x95, 0xd8, 0x17, 0xbc, 0xa7,
	0x82, 0x43, 0xd2, 0xbe, 0x62, 0x9b, 0x73, 0x85, 0x51, 0x20, 0xf8, 0x87, 0x72, 0x85, 0x25, 0xb1,
	0x3e, 0x9c, 0x56, 0x82, 0x4c, 0xc9, 0x47, 0x2a, 0x39, 0xa8, 0xb1, 0x0e, 0x9c, 0xac, 0xcb, 0x77,
	0x10, 0x92, 0xd7, 0x62, 0xf4, 0x94, 0xac, 0xa9, 0x05, 0x99, 0x6c, 0xa8, 0x5d, 0x6b, 0x6b, 0x52,
	0x69, 0x5c, 0x16, 0xa4, 0x37, 0x63, 0x4f, 0x87, 0xe6, 0x3d, 0xdb, 0x94, 0x3d, 0x81, 0xba, 0x0a,
	0x30, 0x11, 0x7c, 0xd3, 0xae, 0x75, 0x5b, 0xfd, 0x63, 0x37, 0x9c, 0xba, 0x97, 0x1a, 0x78, 0x86,
	0xb3, 0x3e, 0x40, 0xe0, 0x27, 0xe1, 0x97, 0x04, 0xb3, 0x58, 0xf1, 0x9c, 0x5c, 0xcc, 0x9d, 0xf9,
	0x4b, 0xa1, 0xcf, 0xc0, 0x70, 0x2b, 0x79, 0x25, 0x97, 0xde, 0xf2, 0x12, 0xd7, 0x3f, 0x94, 0x18,
	0x87, 0xfc, 0x8f, 0xd9, 0xf2, 0xdb, 0xeb, 0xce, 0x04, 0x1a, 0xa3, 0x4f, 0xdf, 0x13, 0x8c, 0xd9,
	0x53, 0xa8, 0xc7, 0x09, 0xc6, 0x8a, 0x3b, 0x14, 0xda, 0xd2, 0xad, 0xc7, 0x32, 0x7d, 0xfb, 0xe6,
	0xdb, 0x95, 0x67, 0x14, 0xf6, 0x02, 0x9a, 0x01, 0x4a, 0x95, 0x2d, 0x85, 0xe2, 0x47, 0xff, 0xbb,
	0x76, 0x62, 0xe7, 0x2b, 0xd4, 0x69, 0x6a, 0xf6, 0x08, 0x8e, 0x69, 0x31, 0xc9, 0x63, 0x51, 0x1c,
	0xc3, 0x3d, 0xd0, 0x2d, 0xcd, 0xdd, 0xda, 0x61, 0x83, 0xbe, 0x6e, 0x49, 0x4a, 0xe7, 0x25, 0xdc,
	0x2c, 0x08, 0xbb, 0x03, 0xb5, 0xdf, 0x22, 0x2f, 0x52, 0xf4, 0x92, 0x9d, 0x80, 0xb3, 0x2a, 0x0e,
	0xb1, 0xb3, 0x2a, 0xac, 0x7a, 0x92, 0xb2, 0xb5, 0x56, 0xb1, 0xd6, 0x3c, 0x67, 0x35, 0x6d, 0xd0,
	0xc7, 0x62, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x52, 0xbb, 0x61, 0x9e, 0x6c, 0x04, 0x00, 0x00,
}
