// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared/filter/protocol/message.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	shared/filter/protocol/message.proto

It has these top-level messages:
	Client_FilterReq
	Data
	Server_FilterResp
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Client_FilterReq struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *Client_FilterReq) Reset()                    { *m = Client_FilterReq{} }
func (m *Client_FilterReq) String() string            { return proto.CompactTextString(m) }
func (*Client_FilterReq) ProtoMessage()               {}
func (*Client_FilterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Client_FilterReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Data struct {
	Keyword []string `protobuf:"bytes,1,rep,name=keyword" json:"keyword,omitempty"`
	NewText string   `protobuf:"bytes,2,opt,name=newText" json:"newText,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Data) GetKeyword() []string {
	if m != nil {
		return m.Keyword
	}
	return nil
}

func (m *Data) GetNewText() string {
	if m != nil {
		return m.NewText
	}
	return ""
}

type Server_FilterResp struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Data *Data  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *Server_FilterResp) Reset()                    { *m = Server_FilterResp{} }
func (m *Server_FilterResp) String() string            { return proto.CompactTextString(m) }
func (*Server_FilterResp) ProtoMessage()               {}
func (*Server_FilterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Server_FilterResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Server_FilterResp) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Server_FilterResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Client_FilterReq)(nil), "protocol.Client_FilterReq")
	proto.RegisterType((*Data)(nil), "protocol.Data")
	proto.RegisterType((*Server_FilterResp)(nil), "protocol.Server_FilterResp")
}

func init() { proto.RegisterFile("shared/filter/protocol/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xcd, 0x4e, 0x84, 0x30,
	0x10, 0xc7, 0x83, 0xe0, 0xd7, 0x98, 0x18, 0xec, 0xa9, 0x47, 0xd2, 0x78, 0xf0, 0x60, 0x20, 0xd1,
	0x9b, 0x57, 0x8d, 0x0f, 0x50, 0xbd, 0x1a, 0x53, 0xe9, 0x88, 0x44, 0x68, 0xd9, 0x76, 0xb2, 0xec,
	0xbe, 0xfd, 0xa6, 0xb3, 0xb0, 0xb7, 0xf9, 0x7f, 0xe5, 0x37, 0x70, 0x1f, 0xff, 0x4c, 0x40, 0xdb,
	0xfc, 0xf6, 0x03, 0x61, 0x68, 0xa6, 0xe0, 0xc9, 0xb7, 0x7e, 0x68, 0x46, 0x8c, 0xd1, 0x74, 0x58,
	0xb3, 0x21, 0xae, 0x56, 0x5f, 0x3d, 0x42, 0xf9, 0x3a, 0xf4, 0xe8, 0xe8, 0xfb, 0x9d, 0x17, 0x1a,
	0x37, 0x42, 0xc2, 0x65, 0xeb, 0x1d, 0xa1, 0x23, 0x99, 0x55, 0xd9, 0xc3, 0xb5, 0x5e, 0xa5, 0x7a,
	0x81, 0xe2, 0xcd, 0x90, 0x49, 0x8d, 0x7f, 0xdc, 0xcf, 0x3e, 0x58, 0x99, 0x55, 0x79, 0x6a, 0x2c,
	0x32, 0x25, 0x0e, 0xe7, 0x4f, 0xdc, 0x91, 0x3c, 0x3b, 0x6e, 0x17, 0xa9, 0xbe, 0xe0, 0xee, 0x03,
	0xc3, 0x16, 0xc3, 0x89, 0x14, 0x27, 0x21, 0xa0, 0x68, 0xbd, 0x45, 0xe6, 0x9c, 0x6b, 0xbe, 0x85,
	0x82, 0xc2, 0x1a, 0x32, 0xbc, 0xbf, 0x79, 0xba, 0xad, 0xd7, 0x5f, 0xeb, 0x84, 0xd6, 0x9c, 0x89,
	0x12, 0xf2, 0x31, 0x76, 0x32, 0x67, 0x44, 0x3a, 0x7f, 0x2e, 0xb8, 0xf6, 0x7c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x2a, 0xf8, 0xd5, 0xa2, 0x01, 0x01, 0x00, 0x00,
}
