// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: smsg/admin_msg.proto

package smsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	_ "sanguosha.com/sgs_herox/proto/def"
	gameconf "sanguosha.com/sgs_herox/proto/gameconf"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeUserDataTyp int32

const (
	ChangeUserDataTyp_CUDInvalid ChangeUserDataTyp = 0
	ChangeUserDataTyp_CUDDelItem ChangeUserDataTyp = 1 //删除道具
)

// Enum value maps for ChangeUserDataTyp.
var (
	ChangeUserDataTyp_name = map[int32]string{
		0: "CUDInvalid",
		1: "CUDDelItem",
	}
	ChangeUserDataTyp_value = map[string]int32{
		"CUDInvalid": 0,
		"CUDDelItem": 1,
	}
)

func (x ChangeUserDataTyp) Enum() *ChangeUserDataTyp {
	p := new(ChangeUserDataTyp)
	*p = x
	return p
}

func (x ChangeUserDataTyp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeUserDataTyp) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[0].Descriptor()
}

func (ChangeUserDataTyp) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[0]
}

func (x ChangeUserDataTyp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeUserDataTyp.Descriptor instead.
func (ChangeUserDataTyp) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{0}
}

//GM命令类型
type GMType int32

const (
	GMType_GMTInvalid     GMType = 0
	GMType_GMTAccountLock GMType = 1
	GMType_GMTChatLock    GMType = 2
)

// Enum value maps for GMType.
var (
	GMType_name = map[int32]string{
		0: "GMTInvalid",
		1: "GMTAccountLock",
		2: "GMTChatLock",
	}
	GMType_value = map[string]int32{
		"GMTInvalid":     0,
		"GMTAccountLock": 1,
		"GMTChatLock":    2,
	}
)

func (x GMType) Enum() *GMType {
	p := new(GMType)
	*p = x
	return p
}

func (x GMType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GMType) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[1].Descriptor()
}

func (GMType) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[1]
}

func (x GMType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GMType.Descriptor instead.
func (GMType) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{1}
}

type PuEnAddProp_OptType int32

const (
	PuEnAddProp_AddProp     PuEnAddProp_OptType = 0 //加道具并减道具
	PuEnAddProp_AddPropOnly PuEnAddProp_OptType = 1 //只加道具
	PuEnAddProp_SubProp     PuEnAddProp_OptType = 2 //加道具并扣道具
	PuEnAddProp_SubPropOnly PuEnAddProp_OptType = 3 //只扣道具
	PuEnAddProp_ShopBuy     PuEnAddProp_OptType = 4 //商城购买（和AddProp功能相同，为了区分而加）
)

// Enum value maps for PuEnAddProp_OptType.
var (
	PuEnAddProp_OptType_name = map[int32]string{
		0: "AddProp",
		1: "AddPropOnly",
		2: "SubProp",
		3: "SubPropOnly",
		4: "ShopBuy",
	}
	PuEnAddProp_OptType_value = map[string]int32{
		"AddProp":     0,
		"AddPropOnly": 1,
		"SubProp":     2,
		"SubPropOnly": 3,
		"ShopBuy":     4,
	}
)

func (x PuEnAddProp_OptType) Enum() *PuEnAddProp_OptType {
	p := new(PuEnAddProp_OptType)
	*p = x
	return p
}

func (x PuEnAddProp_OptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PuEnAddProp_OptType) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[2].Descriptor()
}

func (PuEnAddProp_OptType) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[2]
}

func (x PuEnAddProp_OptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PuEnAddProp_OptType.Descriptor instead.
func (PuEnAddProp_OptType) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{0, 0}
}

type PuEnRespAddProp_ErrCode int32

const (
	PuEnRespAddProp_Invalid             PuEnRespAddProp_ErrCode = 0
	PuEnRespAddProp_ErrSystem           PuEnRespAddProp_ErrCode = 1
	PuEnRespAddProp_ErrSubPropNotEnough PuEnRespAddProp_ErrCode = 2
	PuEnRespAddProp_ErrUserError        PuEnRespAddProp_ErrCode = 3
	PuEnRespAddProp_ErrPackageFull      PuEnRespAddProp_ErrCode = 4
	PuEnRespAddProp_ErrAddPropNotExist  PuEnRespAddProp_ErrCode = 5 //加的物品不存在
	PuEnRespAddProp_ErrItemAlreadyOwned PuEnRespAddProp_ErrCode = 6 //物品已拥有（目前皮肤和英雄不可重复购买）
	PuEnRespAddProp_ErrSubItem          PuEnRespAddProp_ErrCode = 7 //扣除道具失败
)

// Enum value maps for PuEnRespAddProp_ErrCode.
var (
	PuEnRespAddProp_ErrCode_name = map[int32]string{
		0: "Invalid",
		1: "ErrSystem",
		2: "ErrSubPropNotEnough",
		3: "ErrUserError",
		4: "ErrPackageFull",
		5: "ErrAddPropNotExist",
		6: "ErrItemAlreadyOwned",
		7: "ErrSubItem",
	}
	PuEnRespAddProp_ErrCode_value = map[string]int32{
		"Invalid":             0,
		"ErrSystem":           1,
		"ErrSubPropNotEnough": 2,
		"ErrUserError":        3,
		"ErrPackageFull":      4,
		"ErrAddPropNotExist":  5,
		"ErrItemAlreadyOwned": 6,
		"ErrSubItem":          7,
	}
)

func (x PuEnRespAddProp_ErrCode) Enum() *PuEnRespAddProp_ErrCode {
	p := new(PuEnRespAddProp_ErrCode)
	*p = x
	return p
}

func (x PuEnRespAddProp_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PuEnRespAddProp_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[3].Descriptor()
}

func (PuEnRespAddProp_ErrCode) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[3]
}

func (x PuEnRespAddProp_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PuEnRespAddProp_ErrCode.Descriptor instead.
func (PuEnRespAddProp_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{1, 0}
}

type PuEnRespBatchAddProp_ErrCode int32

const (
	PuEnRespBatchAddProp_Invalid      PuEnRespBatchAddProp_ErrCode = 0
	PuEnRespBatchAddProp_UserNotExist PuEnRespBatchAddProp_ErrCode = 1
	PuEnRespBatchAddProp_PackageFull  PuEnRespBatchAddProp_ErrCode = 2
)

// Enum value maps for PuEnRespBatchAddProp_ErrCode.
var (
	PuEnRespBatchAddProp_ErrCode_name = map[int32]string{
		0: "Invalid",
		1: "UserNotExist",
		2: "PackageFull",
	}
	PuEnRespBatchAddProp_ErrCode_value = map[string]int32{
		"Invalid":      0,
		"UserNotExist": 1,
		"PackageFull":  2,
	}
)

func (x PuEnRespBatchAddProp_ErrCode) Enum() *PuEnRespBatchAddProp_ErrCode {
	p := new(PuEnRespBatchAddProp_ErrCode)
	*p = x
	return p
}

func (x PuEnRespBatchAddProp_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PuEnRespBatchAddProp_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[4].Descriptor()
}

func (PuEnRespBatchAddProp_ErrCode) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[4]
}

func (x PuEnRespBatchAddProp_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PuEnRespBatchAddProp_ErrCode.Descriptor instead.
func (PuEnRespBatchAddProp_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{3, 0}
}

type AdEnRespChangeUserData_ErrCode int32

const (
	AdEnRespChangeUserData_Invalid    AdEnRespChangeUserData_ErrCode = 0
	AdEnRespChangeUserData_ParamError AdEnRespChangeUserData_ErrCode = 1 //参数有误
)

// Enum value maps for AdEnRespChangeUserData_ErrCode.
var (
	AdEnRespChangeUserData_ErrCode_name = map[int32]string{
		0: "Invalid",
		1: "ParamError",
	}
	AdEnRespChangeUserData_ErrCode_value = map[string]int32{
		"Invalid":    0,
		"ParamError": 1,
	}
)

func (x AdEnRespChangeUserData_ErrCode) Enum() *AdEnRespChangeUserData_ErrCode {
	p := new(AdEnRespChangeUserData_ErrCode)
	*p = x
	return p
}

func (x AdEnRespChangeUserData_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdEnRespChangeUserData_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[5].Descriptor()
}

func (AdEnRespChangeUserData_ErrCode) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[5]
}

func (x AdEnRespChangeUserData_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdEnRespChangeUserData_ErrCode.Descriptor instead.
func (AdEnRespChangeUserData_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{8, 0}
}

type AdAllRespReload_ErrCode int32

const (
	AdAllRespReload_Invalid   AdAllRespReload_ErrCode = 0
	AdAllRespReload_ReloadErr AdAllRespReload_ErrCode = 1
)

// Enum value maps for AdAllRespReload_ErrCode.
var (
	AdAllRespReload_ErrCode_name = map[int32]string{
		0: "Invalid",
		1: "ReloadErr",
	}
	AdAllRespReload_ErrCode_value = map[string]int32{
		"Invalid":   0,
		"ReloadErr": 1,
	}
)

func (x AdAllRespReload_ErrCode) Enum() *AdAllRespReload_ErrCode {
	p := new(AdAllRespReload_ErrCode)
	*p = x
	return p
}

func (x AdAllRespReload_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdAllRespReload_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[6].Descriptor()
}

func (AdAllRespReload_ErrCode) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[6]
}

func (x AdAllRespReload_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdAllRespReload_ErrCode.Descriptor instead.
func (AdAllRespReload_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{10, 0}
}

type AdAllRespCloseServer_ErrCode int32

const (
	AdAllRespCloseServer_Invalid  AdAllRespCloseServer_ErrCode = 0
	AdAllRespCloseServer_CloseErr AdAllRespCloseServer_ErrCode = 1
)

// Enum value maps for AdAllRespCloseServer_ErrCode.
var (
	AdAllRespCloseServer_ErrCode_name = map[int32]string{
		0: "Invalid",
		1: "CloseErr",
	}
	AdAllRespCloseServer_ErrCode_value = map[string]int32{
		"Invalid":  0,
		"CloseErr": 1,
	}
)

func (x AdAllRespCloseServer_ErrCode) Enum() *AdAllRespCloseServer_ErrCode {
	p := new(AdAllRespCloseServer_ErrCode)
	*p = x
	return p
}

func (x AdAllRespCloseServer_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdAllRespCloseServer_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[7].Descriptor()
}

func (AdAllRespCloseServer_ErrCode) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[7]
}

func (x AdAllRespCloseServer_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdAllRespCloseServer_ErrCode.Descriptor instead.
func (AdAllRespCloseServer_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{12, 0}
}

type AdAllRespGMCommand_ErrCode int32

const (
	AdAllRespGMCommand_Invalid        AdAllRespGMCommand_ErrCode = 0
	AdAllRespGMCommand_LoadUserError  AdAllRespGMCommand_ErrCode = 1
	AdAllRespGMCommand_GMTypeNotExist AdAllRespGMCommand_ErrCode = 2
)

// Enum value maps for AdAllRespGMCommand_ErrCode.
var (
	AdAllRespGMCommand_ErrCode_name = map[int32]string{
		0: "Invalid",
		1: "LoadUserError",
		2: "GMTypeNotExist",
	}
	AdAllRespGMCommand_ErrCode_value = map[string]int32{
		"Invalid":        0,
		"LoadUserError":  1,
		"GMTypeNotExist": 2,
	}
)

func (x AdAllRespGMCommand_ErrCode) Enum() *AdAllRespGMCommand_ErrCode {
	p := new(AdAllRespGMCommand_ErrCode)
	*p = x
	return p
}

func (x AdAllRespGMCommand_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdAllRespGMCommand_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[8].Descriptor()
}

func (AdAllRespGMCommand_ErrCode) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[8]
}

func (x AdAllRespGMCommand_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdAllRespGMCommand_ErrCode.Descriptor instead.
func (AdAllRespGMCommand_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{14, 0}
}

type AdAllRespMetrics_MetricsType int32

const (
	AdAllRespMetrics_Invalid     AdAllRespMetrics_MetricsType = 0
	AdAllRespMetrics_OnlineCount AdAllRespMetrics_MetricsType = 1 //在线人数
	AdAllRespMetrics_GameCount   AdAllRespMetrics_MetricsType = 2 //游戏数量
	AdAllRespMetrics_RoomCount   AdAllRespMetrics_MetricsType = 3 //房间数量
)

// Enum value maps for AdAllRespMetrics_MetricsType.
var (
	AdAllRespMetrics_MetricsType_name = map[int32]string{
		0: "Invalid",
		1: "OnlineCount",
		2: "GameCount",
		3: "RoomCount",
	}
	AdAllRespMetrics_MetricsType_value = map[string]int32{
		"Invalid":     0,
		"OnlineCount": 1,
		"GameCount":   2,
		"RoomCount":   3,
	}
)

func (x AdAllRespMetrics_MetricsType) Enum() *AdAllRespMetrics_MetricsType {
	p := new(AdAllRespMetrics_MetricsType)
	*p = x
	return p
}

func (x AdAllRespMetrics_MetricsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdAllRespMetrics_MetricsType) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[9].Descriptor()
}

func (AdAllRespMetrics_MetricsType) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[9]
}

func (x AdAllRespMetrics_MetricsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdAllRespMetrics_MetricsType.Descriptor instead.
func (AdAllRespMetrics_MetricsType) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{17, 0}
}

type AsAllReqMSGMonitor_Type int32

const (
	AsAllReqMSGMonitor_Invalid                AsAllReqMSGMonitor_Type = 0
	AsAllReqMSGMonitor_Gate_StartRECReq       AsAllReqMSGMonitor_Type = 1  //开始记录请求次数
	AsAllReqMSGMonitor_Gate_StopGetRECReq     AsAllReqMSGMonitor_Type = 2  //停止记录并取回请求次数记录
	AsAllReqMSGMonitor_Gate_PrintSlowResponse AsAllReqMSGMonitor_Type = 3  //打印消息响应的慢日志
	AsAllReqMSGMonitor_Gate_PrintUserMsgInOut AsAllReqMSGMonitor_Type = 4  //打印玩家消息进出日志
	AsAllReqMSGMonitor_All_PrintUserMsgDetail AsAllReqMSGMonitor_Type = 5  //打印服务器收到玩家消息的详细信息
	AsAllReqMSGMonitor_All_StopPrint          AsAllReqMSGMonitor_Type = 10 //停止打印
)

// Enum value maps for AsAllReqMSGMonitor_Type.
var (
	AsAllReqMSGMonitor_Type_name = map[int32]string{
		0:  "Invalid",
		1:  "Gate_StartRECReq",
		2:  "Gate_StopGetRECReq",
		3:  "Gate_PrintSlowResponse",
		4:  "Gate_PrintUserMsgInOut",
		5:  "All_PrintUserMsgDetail",
		10: "All_StopPrint",
	}
	AsAllReqMSGMonitor_Type_value = map[string]int32{
		"Invalid":                0,
		"Gate_StartRECReq":       1,
		"Gate_StopGetRECReq":     2,
		"Gate_PrintSlowResponse": 3,
		"Gate_PrintUserMsgInOut": 4,
		"All_PrintUserMsgDetail": 5,
		"All_StopPrint":          10,
	}
)

func (x AsAllReqMSGMonitor_Type) Enum() *AsAllReqMSGMonitor_Type {
	p := new(AsAllReqMSGMonitor_Type)
	*p = x
	return p
}

func (x AsAllReqMSGMonitor_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AsAllReqMSGMonitor_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[10].Descriptor()
}

func (AsAllReqMSGMonitor_Type) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[10]
}

func (x AsAllReqMSGMonitor_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AsAllReqMSGMonitor_Type.Descriptor instead.
func (AsAllReqMSGMonitor_Type) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{18, 0}
}

type AsAllRespMSGMonitor_ErrCode int32

const (
	AsAllRespMSGMonitor_Invalid        AsAllRespMSGMonitor_ErrCode = 0
	AsAllRespMSGMonitor_GMTypeNotExist AsAllRespMSGMonitor_ErrCode = 1
)

// Enum value maps for AsAllRespMSGMonitor_ErrCode.
var (
	AsAllRespMSGMonitor_ErrCode_name = map[int32]string{
		0: "Invalid",
		1: "GMTypeNotExist",
	}
	AsAllRespMSGMonitor_ErrCode_value = map[string]int32{
		"Invalid":        0,
		"GMTypeNotExist": 1,
	}
)

func (x AsAllRespMSGMonitor_ErrCode) Enum() *AsAllRespMSGMonitor_ErrCode {
	p := new(AsAllRespMSGMonitor_ErrCode)
	*p = x
	return p
}

func (x AsAllRespMSGMonitor_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AsAllRespMSGMonitor_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_smsg_admin_msg_proto_enumTypes[11].Descriptor()
}

func (AsAllRespMSGMonitor_ErrCode) Type() protoreflect.EnumType {
	return &file_smsg_admin_msg_proto_enumTypes[11]
}

func (x AsAllRespMSGMonitor_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AsAllRespMSGMonitor_ErrCode.Descriptor instead.
func (AsAllRespMSGMonitor_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{19, 0}
}

//加道具请求
type PuEnAddProp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptType         PuEnAddProp_OptType  `protobuf:"varint,3,opt,name=optType,proto3,enum=smsg.PuEnAddProp_OptType" json:"optType,omitempty"`
	ItemsAdd        []*gameconf.PropPack `protobuf:"bytes,4,rep,name=itemsAdd,proto3" json:"itemsAdd,omitempty"`                //要加的道具组
	ItemsSub        []*gameconf.PropPack `protobuf:"bytes,5,rep,name=itemsSub,proto3" json:"itemsSub,omitempty"`                //要扣的道具组
	ForceHideEffect bool                 `protobuf:"varint,6,opt,name=forceHideEffect,proto3" json:"forceHideEffect,omitempty"` //隐藏获得提示
	BuyID           int32                `protobuf:"varint,7,opt,name=buyID,proto3" json:"buyID,omitempty"`                     //如果是购买，购买项的唯一ID
	ShopTab         int32                `protobuf:"varint,13,opt,name=shopTab,proto3" json:"shopTab,omitempty"`                // 如果是购买, 购买项的商城类型
	BuyNum          int32                `protobuf:"varint,8,opt,name=buyNum,proto3" json:"buyNum,omitempty"`                   //购买的数量
	BuyName         string               `protobuf:"bytes,9,opt,name=buyName,proto3" json:"buyName,omitempty"`                  //购买物品的名称
	Why             int32                `protobuf:"varint,10,opt,name=why,proto3" json:"why,omitempty"`
	GetID           string               `protobuf:"bytes,12,opt,name=getID,proto3" json:"getID,omitempty"`
}

func (x *PuEnAddProp) Reset() {
	*x = PuEnAddProp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuEnAddProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuEnAddProp) ProtoMessage() {}

func (x *PuEnAddProp) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuEnAddProp.ProtoReflect.Descriptor instead.
func (*PuEnAddProp) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{0}
}

func (x *PuEnAddProp) GetOptType() PuEnAddProp_OptType {
	if x != nil {
		return x.OptType
	}
	return PuEnAddProp_AddProp
}

func (x *PuEnAddProp) GetItemsAdd() []*gameconf.PropPack {
	if x != nil {
		return x.ItemsAdd
	}
	return nil
}

func (x *PuEnAddProp) GetItemsSub() []*gameconf.PropPack {
	if x != nil {
		return x.ItemsSub
	}
	return nil
}

func (x *PuEnAddProp) GetForceHideEffect() bool {
	if x != nil {
		return x.ForceHideEffect
	}
	return false
}

func (x *PuEnAddProp) GetBuyID() int32 {
	if x != nil {
		return x.BuyID
	}
	return 0
}

func (x *PuEnAddProp) GetShopTab() int32 {
	if x != nil {
		return x.ShopTab
	}
	return 0
}

func (x *PuEnAddProp) GetBuyNum() int32 {
	if x != nil {
		return x.BuyNum
	}
	return 0
}

func (x *PuEnAddProp) GetBuyName() string {
	if x != nil {
		return x.BuyName
	}
	return ""
}

func (x *PuEnAddProp) GetWhy() int32 {
	if x != nil {
		return x.Why
	}
	return 0
}

func (x *PuEnAddProp) GetGetID() string {
	if x != nil {
		return x.GetID
	}
	return ""
}

type PuEnRespAddProp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode PuEnRespAddProp_ErrCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=smsg.PuEnRespAddProp_ErrCode" json:"errCode,omitempty"`
	ErrMsg  string                  `protobuf:"bytes,4,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Get     []*gameconf.PropPack    `protobuf:"bytes,5,rep,name=get,proto3" json:"get,omitempty"`
}

func (x *PuEnRespAddProp) Reset() {
	*x = PuEnRespAddProp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuEnRespAddProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuEnRespAddProp) ProtoMessage() {}

func (x *PuEnRespAddProp) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuEnRespAddProp.ProtoReflect.Descriptor instead.
func (*PuEnRespAddProp) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PuEnRespAddProp) GetErrCode() PuEnRespAddProp_ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return PuEnRespAddProp_Invalid
}

func (x *PuEnRespAddProp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *PuEnRespAddProp) GetGet() []*gameconf.PropPack {
	if x != nil {
		return x.Get
	}
	return nil
}

//加道具请求（一次加多个）
type PuEnReqBatchAddProp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddList []*PuEnReqBatchAddProp_Item `protobuf:"bytes,3,rep,name=addList,proto3" json:"addList,omitempty"`
}

func (x *PuEnReqBatchAddProp) Reset() {
	*x = PuEnReqBatchAddProp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuEnReqBatchAddProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuEnReqBatchAddProp) ProtoMessage() {}

func (x *PuEnReqBatchAddProp) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuEnReqBatchAddProp.ProtoReflect.Descriptor instead.
func (*PuEnReqBatchAddProp) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{2}
}

func (x *PuEnReqBatchAddProp) GetAddList() []*PuEnReqBatchAddProp_Item {
	if x != nil {
		return x.AddList
	}
	return nil
}

type PuEnRespBatchAddProp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode PuEnRespBatchAddProp_ErrCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=smsg.PuEnRespBatchAddProp_ErrCode" json:"errCode,omitempty"`
	Get     []*gameconf.PropPack         `protobuf:"bytes,4,rep,name=get,proto3" json:"get,omitempty"`
}

func (x *PuEnRespBatchAddProp) Reset() {
	*x = PuEnRespBatchAddProp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuEnRespBatchAddProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuEnRespBatchAddProp) ProtoMessage() {}

func (x *PuEnRespBatchAddProp) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuEnRespBatchAddProp.ProtoReflect.Descriptor instead.
func (*PuEnRespBatchAddProp) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{3}
}

func (x *PuEnRespBatchAddProp) GetErrCode() PuEnRespBatchAddProp_ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return PuEnRespBatchAddProp_Invalid
}

func (x *PuEnRespBatchAddProp) GetGet() []*gameconf.PropPack {
	if x != nil {
		return x.Get
	}
	return nil
}

type DelUserItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropType int32 `protobuf:"varint,1,opt,name=propType,proto3" json:"propType,omitempty"`
	PropID   int32 `protobuf:"varint,2,opt,name=propID,proto3" json:"propID,omitempty"`
	Num      int32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	DelAll   bool  `protobuf:"varint,4,opt,name=delAll,proto3" json:"delAll,omitempty"`
}

func (x *DelUserItem) Reset() {
	*x = DelUserItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserItem) ProtoMessage() {}

func (x *DelUserItem) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserItem.ProtoReflect.Descriptor instead.
func (*DelUserItem) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{4}
}

func (x *DelUserItem) GetPropType() int32 {
	if x != nil {
		return x.PropType
	}
	return 0
}

func (x *DelUserItem) GetPropID() int32 {
	if x != nil {
		return x.PropID
	}
	return 0
}

func (x *DelUserItem) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *DelUserItem) GetDelAll() bool {
	if x != nil {
		return x.DelAll
	}
	return false
}

type ReqQueryBackup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timetag int64 `protobuf:"varint,3,opt,name=timetag,proto3" json:"timetag,omitempty"`
}

func (x *ReqQueryBackup) Reset() {
	*x = ReqQueryBackup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryBackup) ProtoMessage() {}

func (x *ReqQueryBackup) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryBackup.ProtoReflect.Descriptor instead.
func (*ReqQueryBackup) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{5}
}

func (x *ReqQueryBackup) GetTimetag() int64 {
	if x != nil {
		return x.Timetag
	}
	return 0
}

type RespQueryBackup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode uint32 `protobuf:"varint,3,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Backup  string `protobuf:"bytes,4,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *RespQueryBackup) Reset() {
	*x = RespQueryBackup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespQueryBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespQueryBackup) ProtoMessage() {}

func (x *RespQueryBackup) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespQueryBackup.ProtoReflect.Descriptor instead.
func (*RespQueryBackup) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{6}
}

func (x *RespQueryBackup) GetErrCode() uint32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RespQueryBackup) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

type AdEnReqChangeUserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        ChangeUserDataTyp `protobuf:"varint,3,opt,name=type,proto3,enum=smsg.ChangeUserDataTyp" json:"type,omitempty"`
	DelUserItem *DelUserItem      `protobuf:"bytes,4,opt,name=delUserItem,proto3" json:"delUserItem,omitempty"`
}

func (x *AdEnReqChangeUserData) Reset() {
	*x = AdEnReqChangeUserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdEnReqChangeUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdEnReqChangeUserData) ProtoMessage() {}

func (x *AdEnReqChangeUserData) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdEnReqChangeUserData.ProtoReflect.Descriptor instead.
func (*AdEnReqChangeUserData) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{7}
}

func (x *AdEnReqChangeUserData) GetType() ChangeUserDataTyp {
	if x != nil {
		return x.Type
	}
	return ChangeUserDataTyp_CUDInvalid
}

func (x *AdEnReqChangeUserData) GetDelUserItem() *DelUserItem {
	if x != nil {
		return x.DelUserItem
	}
	return nil
}

type AdEnRespChangeUserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode AdEnRespChangeUserData_ErrCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=smsg.AdEnRespChangeUserData_ErrCode" json:"errCode,omitempty"`
	ErrMsg  string                         `protobuf:"bytes,4,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *AdEnRespChangeUserData) Reset() {
	*x = AdEnRespChangeUserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdEnRespChangeUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdEnRespChangeUserData) ProtoMessage() {}

func (x *AdEnRespChangeUserData) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdEnRespChangeUserData.ProtoReflect.Descriptor instead.
func (*AdEnRespChangeUserData) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{8}
}

func (x *AdEnRespChangeUserData) GetErrCode() AdEnRespChangeUserData_ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return AdEnRespChangeUserData_Invalid
}

func (x *AdEnRespChangeUserData) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

//请求重载配置
type AdAllReqReload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdAllReqReload) Reset() {
	*x = AdAllReqReload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllReqReload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllReqReload) ProtoMessage() {}

func (x *AdAllReqReload) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllReqReload.ProtoReflect.Descriptor instead.
func (*AdAllReqReload) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{9}
}

type AdAllRespReload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode AdAllRespReload_ErrCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=smsg.AdAllRespReload_ErrCode" json:"errCode,omitempty"`
	ErrMsg  string                  `protobuf:"bytes,4,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *AdAllRespReload) Reset() {
	*x = AdAllRespReload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllRespReload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllRespReload) ProtoMessage() {}

func (x *AdAllRespReload) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllRespReload.ProtoReflect.Descriptor instead.
func (*AdAllRespReload) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{10}
}

func (x *AdAllRespReload) GetErrCode() AdAllRespReload_ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return AdAllRespReload_Invalid
}

func (x *AdAllRespReload) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type AdAllReqCloseServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdAllReqCloseServer) Reset() {
	*x = AdAllReqCloseServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllReqCloseServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllReqCloseServer) ProtoMessage() {}

func (x *AdAllReqCloseServer) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllReqCloseServer.ProtoReflect.Descriptor instead.
func (*AdAllReqCloseServer) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{11}
}

type AdAllRespCloseServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode AdAllRespCloseServer_ErrCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=smsg.AdAllRespCloseServer_ErrCode" json:"errCode,omitempty"`
	ErrMsg  string                       `protobuf:"bytes,4,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *AdAllRespCloseServer) Reset() {
	*x = AdAllRespCloseServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllRespCloseServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllRespCloseServer) ProtoMessage() {}

func (x *AdAllRespCloseServer) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllRespCloseServer.ProtoReflect.Descriptor instead.
func (*AdAllRespCloseServer) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{12}
}

func (x *AdAllRespCloseServer) GetErrCode() AdAllRespCloseServer_ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return AdAllRespCloseServer_Invalid
}

func (x *AdAllRespCloseServer) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

//admin对其它服务器发出的命令
type AdAllReqGMCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gmtype GMType                  `protobuf:"varint,3,opt,name=gmtype,proto3,enum=smsg.GMType" json:"gmtype,omitempty"`
	Lock   *AdAllReqGMCommand_Lock `protobuf:"bytes,4,opt,name=lock,proto3" json:"lock,omitempty"`
}

func (x *AdAllReqGMCommand) Reset() {
	*x = AdAllReqGMCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllReqGMCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllReqGMCommand) ProtoMessage() {}

func (x *AdAllReqGMCommand) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllReqGMCommand.ProtoReflect.Descriptor instead.
func (*AdAllReqGMCommand) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{13}
}

func (x *AdAllReqGMCommand) GetGmtype() GMType {
	if x != nil {
		return x.Gmtype
	}
	return GMType_GMTInvalid
}

func (x *AdAllReqGMCommand) GetLock() *AdAllReqGMCommand_Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

type AdAllRespGMCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode AdAllRespGMCommand_ErrCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=smsg.AdAllRespGMCommand_ErrCode" json:"errCode,omitempty"`
	ErrMsg  string                     `protobuf:"bytes,4,opt,name=errMsg,proto3" json:"errMsg,omitempty"` //错误消息
	Gmtype  GMType                     `protobuf:"varint,5,opt,name=gmtype,proto3,enum=smsg.GMType" json:"gmtype,omitempty"`
	Lock    *AdAllRespGMCommand_Lock   `protobuf:"bytes,6,opt,name=lock,proto3" json:"lock,omitempty"`
}

func (x *AdAllRespGMCommand) Reset() {
	*x = AdAllRespGMCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllRespGMCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllRespGMCommand) ProtoMessage() {}

func (x *AdAllRespGMCommand) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllRespGMCommand.ProtoReflect.Descriptor instead.
func (*AdAllRespGMCommand) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{14}
}

func (x *AdAllRespGMCommand) GetErrCode() AdAllRespGMCommand_ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return AdAllRespGMCommand_Invalid
}

func (x *AdAllRespGMCommand) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *AdAllRespGMCommand) GetGmtype() GMType {
	if x != nil {
		return x.Gmtype
	}
	return GMType_GMTInvalid
}

func (x *AdAllRespGMCommand) GetLock() *AdAllRespGMCommand_Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

//通知Gate踢出玩家
type AllGaNtfKickUserOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KickAll bool                       `protobuf:"varint,1,opt,name=kickAll,proto3" json:"kickAll,omitempty"`        //是否踢出所有玩家
	UserIds []uint64                   `protobuf:"varint,2,rep,packed,name=userIds,proto3" json:"userIds,omitempty"` //如果不是踢出所有玩家，则踢出这些玩家
	Reason  gameconf.KickUserOutReason `protobuf:"varint,3,opt,name=reason,proto3,enum=gameconf.KickUserOutReason" json:"reason,omitempty"`
}

func (x *AllGaNtfKickUserOut) Reset() {
	*x = AllGaNtfKickUserOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllGaNtfKickUserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllGaNtfKickUserOut) ProtoMessage() {}

func (x *AllGaNtfKickUserOut) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllGaNtfKickUserOut.ProtoReflect.Descriptor instead.
func (*AllGaNtfKickUserOut) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{15}
}

func (x *AllGaNtfKickUserOut) GetKickAll() bool {
	if x != nil {
		return x.KickAll
	}
	return false
}

func (x *AllGaNtfKickUserOut) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *AllGaNtfKickUserOut) GetReason() gameconf.KickUserOutReason {
	if x != nil {
		return x.Reason
	}
	return gameconf.KickUserOutReason_KUOInvalid
}

type AdAllReqMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqTime int64 `protobuf:"varint,3,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
}

func (x *AdAllReqMetrics) Reset() {
	*x = AdAllReqMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllReqMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllReqMetrics) ProtoMessage() {}

func (x *AdAllReqMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllReqMetrics.ProtoReflect.Descriptor instead.
func (*AdAllReqMetrics) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{16}
}

func (x *AdAllReqMetrics) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

type AdAllRespMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*AdAllRespMetrics_Metrics `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ReqTime int64                       `protobuf:"varint,2,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
}

func (x *AdAllRespMetrics) Reset() {
	*x = AdAllRespMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllRespMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllRespMetrics) ProtoMessage() {}

func (x *AdAllRespMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllRespMetrics.ProtoReflect.Descriptor instead.
func (*AdAllRespMetrics) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{17}
}

func (x *AdAllRespMetrics) GetMetrics() []*AdAllRespMetrics_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AdAllRespMetrics) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

//GM监控协议
type AsAllReqMSGMonitor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       AsAllReqMSGMonitor_Type `protobuf:"varint,1,opt,name=type,proto3,enum=smsg.AsAllReqMSGMonitor_Type" json:"type,omitempty"`
	UserId     uint64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	SlowerThan int32                   `protobuf:"varint,3,opt,name=slowerThan,proto3" json:"slowerThan,omitempty"` //SlowResponse的阈值
}

func (x *AsAllReqMSGMonitor) Reset() {
	*x = AsAllReqMSGMonitor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsAllReqMSGMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsAllReqMSGMonitor) ProtoMessage() {}

func (x *AsAllReqMSGMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsAllReqMSGMonitor.ProtoReflect.Descriptor instead.
func (*AsAllReqMSGMonitor) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{18}
}

func (x *AsAllReqMSGMonitor) GetType() AsAllReqMSGMonitor_Type {
	if x != nil {
		return x.Type
	}
	return AsAllReqMSGMonitor_Invalid
}

func (x *AsAllReqMSGMonitor) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AsAllReqMSGMonitor) GetSlowerThan() int32 {
	if x != nil {
		return x.SlowerThan
	}
	return 0
}

type AsAllRespMSGMonitor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode   AsAllRespMSGMonitor_ErrCode       `protobuf:"varint,1,opt,name=errCode,proto3,enum=smsg.AsAllRespMSGMonitor_ErrCode" json:"errCode,omitempty"`
	ErrMsg    string                            `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RECResult *AsAllRespMSGMonitor_RECReqResult `protobuf:"bytes,3,opt,name=RECResult,proto3" json:"RECResult,omitempty"`
}

func (x *AsAllRespMSGMonitor) Reset() {
	*x = AsAllRespMSGMonitor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsAllRespMSGMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsAllRespMSGMonitor) ProtoMessage() {}

func (x *AsAllRespMSGMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsAllRespMSGMonitor.ProtoReflect.Descriptor instead.
func (*AsAllRespMSGMonitor) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{19}
}

func (x *AsAllRespMSGMonitor) GetErrCode() AsAllRespMSGMonitor_ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return AsAllRespMSGMonitor_Invalid
}

func (x *AsAllRespMSGMonitor) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *AsAllRespMSGMonitor) GetRECResult() *AsAllRespMSGMonitor_RECReqResult {
	if x != nil {
		return x.RECResult
	}
	return nil
}

type PuEnReqBatchAddProp_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Why      int32                `protobuf:"varint,1,opt,name=why,proto3" json:"why,omitempty"`
	ItemsAdd []*gameconf.PropPack `protobuf:"bytes,2,rep,name=itemsAdd,proto3" json:"itemsAdd,omitempty"` //要加的道具组
}

func (x *PuEnReqBatchAddProp_Item) Reset() {
	*x = PuEnReqBatchAddProp_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuEnReqBatchAddProp_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuEnReqBatchAddProp_Item) ProtoMessage() {}

func (x *PuEnReqBatchAddProp_Item) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuEnReqBatchAddProp_Item.ProtoReflect.Descriptor instead.
func (*PuEnReqBatchAddProp_Item) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PuEnReqBatchAddProp_Item) GetWhy() int32 {
	if x != nil {
		return x.Why
	}
	return 0
}

func (x *PuEnReqBatchAddProp_Item) GetItemsAdd() []*gameconf.PropPack {
	if x != nil {
		return x.ItemsAdd
	}
	return nil
}

type AdAllReqGMCommand_Lock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIDs []uint64 `protobuf:"varint,1,rep,packed,name=userIDs,proto3" json:"userIDs,omitempty"`
	IsLock  bool     `protobuf:"varint,2,opt,name=isLock,proto3" json:"isLock,omitempty"`
	Time    int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *AdAllReqGMCommand_Lock) Reset() {
	*x = AdAllReqGMCommand_Lock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllReqGMCommand_Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllReqGMCommand_Lock) ProtoMessage() {}

func (x *AdAllReqGMCommand_Lock) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllReqGMCommand_Lock.ProtoReflect.Descriptor instead.
func (*AdAllReqGMCommand_Lock) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{13, 0}
}

func (x *AdAllReqGMCommand_Lock) GetUserIDs() []uint64 {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

func (x *AdAllReqGMCommand_Lock) GetIsLock() bool {
	if x != nil {
		return x.IsLock
	}
	return false
}

func (x *AdAllReqGMCommand_Lock) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type AdAllRespGMCommand_Lock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIDs []uint64 `protobuf:"varint,1,rep,packed,name=userIDs,proto3" json:"userIDs,omitempty"`
}

func (x *AdAllRespGMCommand_Lock) Reset() {
	*x = AdAllRespGMCommand_Lock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllRespGMCommand_Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllRespGMCommand_Lock) ProtoMessage() {}

func (x *AdAllRespGMCommand_Lock) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllRespGMCommand_Lock.ProtoReflect.Descriptor instead.
func (*AdAllRespGMCommand_Lock) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{14, 0}
}

func (x *AdAllRespGMCommand_Lock) GetUserIDs() []uint64 {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type AdAllRespMetrics_Metrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   AdAllRespMetrics_MetricsType `protobuf:"varint,1,opt,name=key,proto3,enum=smsg.AdAllRespMetrics_MetricsType" json:"key,omitempty"`
	Value int32                        `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AdAllRespMetrics_Metrics) Reset() {
	*x = AdAllRespMetrics_Metrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdAllRespMetrics_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdAllRespMetrics_Metrics) ProtoMessage() {}

func (x *AdAllRespMetrics_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdAllRespMetrics_Metrics.ProtoReflect.Descriptor instead.
func (*AdAllRespMetrics_Metrics) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{17, 0}
}

func (x *AdAllRespMetrics_Metrics) GetKey() AdAllRespMetrics_MetricsType {
	if x != nil {
		return x.Key
	}
	return AdAllRespMetrics_Invalid
}

func (x *AdAllRespMetrics_Metrics) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AsAllRespMSGMonitor_RECReqResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateServerId   int32            `protobuf:"varint,1,opt,name=gateServerId,proto3" json:"gateServerId,omitempty"`
	StartTime      int64            `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime        int64            `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Msgs           map[string]int64 `protobuf:"bytes,4,rep,name=msgs,proto3" json:"msgs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //gatemsg的收集器
	StartUserCount int32            `protobuf:"varint,5,opt,name=startUserCount,proto3" json:"startUserCount,omitempty"`                                                                     //gatemsg启动时在线人数
	EndUserCount   int32            `protobuf:"varint,6,opt,name=endUserCount,proto3" json:"endUserCount,omitempty"`                                                                         //gatemsg结束时在线人数
}

func (x *AsAllRespMSGMonitor_RECReqResult) Reset() {
	*x = AsAllRespMSGMonitor_RECReqResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsg_admin_msg_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsAllRespMSGMonitor_RECReqResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsAllRespMSGMonitor_RECReqResult) ProtoMessage() {}

func (x *AsAllRespMSGMonitor_RECReqResult) ProtoReflect() protoreflect.Message {
	mi := &file_smsg_admin_msg_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsAllRespMSGMonitor_RECReqResult.ProtoReflect.Descriptor instead.
func (*AsAllRespMSGMonitor_RECReqResult) Descriptor() ([]byte, []int) {
	return file_smsg_admin_msg_proto_rawDescGZIP(), []int{19, 0}
}

func (x *AsAllRespMSGMonitor_RECReqResult) GetGateServerId() int32 {
	if x != nil {
		return x.GateServerId
	}
	return 0
}

func (x *AsAllRespMSGMonitor_RECReqResult) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AsAllRespMSGMonitor_RECReqResult) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *AsAllRespMSGMonitor_RECReqResult) GetMsgs() map[string]int64 {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *AsAllRespMSGMonitor_RECReqResult) GetStartUserCount() int32 {
	if x != nil {
		return x.StartUserCount
	}
	return 0
}

func (x *AsAllRespMSGMonitor_RECReqResult) GetEndUserCount() int32 {
	if x != nil {
		return x.EndUserCount
	}
	return 0
}

var File_smsg_admin_msg_proto protoreflect.FileDescriptor

var file_smsg_admin_msg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6d, 0x73, 0x67, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x6d, 0x73, 0x67, 0x1a, 0x36, 0x73, 0x61,
	0x6e, 0x67, 0x75, 0x6f, 0x73, 0x68, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x67, 0x73, 0x5f,
	0x68, 0x65, 0x72, 0x6f, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2b, 0x73, 0x61, 0x6e, 0x67, 0x75, 0x6f, 0x73, 0x68, 0x61, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x67, 0x73, 0x5f, 0x68, 0x65, 0x72, 0x6f, 0x78, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x66, 0x2f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xaa, 0x03, 0x0a, 0x0b, 0x50, 0x75, 0x45, 0x6e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f,
	0x70, 0x12, 0x33, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x45, 0x6e, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x70, 0x2e, 0x4f, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6f,
	0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x41,
	0x64, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63,
	0x6f, 0x6e, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x41, 0x64, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x53,
	0x75, 0x62, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63,
	0x6f, 0x6e, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x53, 0x75, 0x62, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x48,
	0x69, 0x64, 0x65, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0f, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x48, 0x69, 0x64, 0x65, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x79, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x62, 0x75, 0x79, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x54, 0x61,
	0x62, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x54, 0x61, 0x62,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x79, 0x4e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x62, 0x75, 0x79, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x77, 0x68, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x74, 0x49, 0x44, 0x22, 0x52, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x4f, 0x6e, 0x6c,
	0x79, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x70, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x70, 0x4f, 0x6e, 0x6c, 0x79, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75, 0x79, 0x10, 0x04, 0x22, 0xb0,
	0x02, 0x0a, 0x0f, 0x50, 0x75, 0x45, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x41, 0x64, 0x64, 0x50, 0x72,
	0x6f, 0x70, 0x12, 0x37, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x45, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x4d, 0x73, 0x67, 0x12, 0x24, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x50, 0x61, 0x63, 0x6b, 0x52, 0x03, 0x67, 0x65, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x70, 0x4e,
	0x6f, 0x74, 0x45, 0x6e, 0x6f, 0x75, 0x67, 0x68, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x72,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e,
	0x45, 0x72, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x04,
	0x12, 0x16, 0x0a, 0x12, 0x45, 0x72, 0x72, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x4e, 0x6f,
	0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x49,
	0x74, 0x65, 0x6d, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x10,
	0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x53, 0x75, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x10,
	0x07, 0x22, 0x99, 0x01, 0x0a, 0x13, 0x50, 0x75, 0x45, 0x6e, 0x52, 0x65, 0x71, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x38, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x6d, 0x73,
	0x67, 0x2e, 0x50, 0x75, 0x45, 0x6e, 0x52, 0x65, 0x71, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x48, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x77,
	0x68, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x77, 0x68, 0x79, 0x12, 0x2e, 0x0a,
	0x08, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x41, 0x64, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x50,
	0x61, 0x63, 0x6b, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x41, 0x64, 0x64, 0x22, 0xb5, 0x01,
	0x0a, 0x14, 0x50, 0x75, 0x45, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x3c, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x50,
	0x75, 0x45, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x64, 0x64, 0x50,
	0x72, 0x6f, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x50, 0x72, 0x6f,
	0x70, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x03, 0x67, 0x65, 0x74, 0x22, 0x39, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x46,
	0x75, 0x6c, 0x6c, 0x10, 0x02, 0x22, 0x6b, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x6c, 0x41, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x41,
	0x6c, 0x6c, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x67, 0x22, 0x43,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x22, 0x79, 0x0a, 0x15, 0x41, 0x64, 0x45, 0x6e, 0x52, 0x65, 0x71, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x64, 0x65, 0x6c,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x98,
	0x01, 0x0a, 0x16, 0x41, 0x64, 0x45, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3e, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x73, 0x6d, 0x73,
	0x67, 0x2e, 0x41, 0x64, 0x45, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0x26, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x64, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x0f,
	0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x37, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x25, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x6f,
	0x61, 0x64, 0x45, 0x72, 0x72, 0x10, 0x01, 0x22, 0x15, 0x0a, 0x13, 0x41, 0x64, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x92,
	0x01, 0x0a, 0x14, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e,
	0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x24, 0x0a,
	0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x45, 0x72,
	0x72, 0x10, 0x01, 0x22, 0xb9, 0x01, 0x0a, 0x11, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x47, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x67, 0x6d, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x6d, 0x73, 0x67,
	0x2e, 0x47, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x67, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x30, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x47, 0x4d, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x04, 0x6c, 0x6f, 0x63,
	0x6b, 0x1a, 0x4c, 0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0xa2, 0x02, 0x0a, 0x12, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x47, 0x4d, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41,
	0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x47, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x24, 0x0a, 0x06, 0x67, 0x6d,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x6d, 0x73,
	0x67, 0x2e, 0x47, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x67, 0x6d, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x31, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x47,
	0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x04, 0x6c,
	0x6f, 0x63, 0x6b, 0x1a, 0x20, 0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x73, 0x22, 0x3d, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x4c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x47, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x10, 0x02, 0x22, 0x7e, 0x0a, 0x13, 0x41, 0x6c, 0x6c, 0x47, 0x61, 0x4e, 0x74, 0x66,
	0x4b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6b,
	0x69, 0x63, 0x6b, 0x41, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6b, 0x69,
	0x63, 0x6b, 0x41, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12,
	0x33, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x71, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x88, 0x02, 0x0a, 0x10, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x38, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41,
	0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x72, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x55, 0x0a, 0x07, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x34, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x64, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x49, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x03, 0x22, 0xaa, 0x02, 0x0a,
	0x12, 0x41, 0x73, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x4d, 0x53, 0x47, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x73, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x4d, 0x53, 0x47, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x73, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x22, 0xa8,
	0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x61, 0x74, 0x65, 0x5f, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x45, 0x43, 0x52, 0x65, 0x71, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x61,
	0x74, 0x65, 0x5f, 0x53, 0x74, 0x6f, 0x70, 0x47, 0x65, 0x74, 0x52, 0x45, 0x43, 0x52, 0x65, 0x71,
	0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x47, 0x61, 0x74, 0x65, 0x5f, 0x50, 0x72, 0x69, 0x6e, 0x74,
	0x53, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x03, 0x12, 0x1a,
	0x0a, 0x16, 0x47, 0x61, 0x74, 0x65, 0x5f, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x73, 0x67, 0x49, 0x6e, 0x4f, 0x75, 0x74, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x6c,
	0x6c, 0x5f, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x5f, 0x53, 0x74,
	0x6f, 0x70, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x10, 0x0a, 0x22, 0x94, 0x04, 0x0a, 0x13, 0x41, 0x73,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x53, 0x47, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x12, 0x3b, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x73, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x4d, 0x53, 0x47, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x44, 0x0a, 0x09, 0x52, 0x45, 0x43, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x6d, 0x73, 0x67,
	0x2e, 0x41, 0x73, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x53, 0x47, 0x4d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x45, 0x43, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x09, 0x52, 0x45, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0xb5, 0x02, 0x0a,
	0x0c, 0x52, 0x45, 0x43, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x04, 0x6d, 0x73, 0x67,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41,
	0x73, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x53, 0x47, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x2e, 0x52, 0x45, 0x43, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e,
	0x4d, 0x73, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x12,
	0x26, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65,
	0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x37, 0x0a, 0x09, 0x4d,
	0x73, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x2a, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e,
	0x47, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x01,
	0x2a, 0x33, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x55, 0x44, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x55, 0x44, 0x44, 0x65, 0x6c, 0x49,
	0x74, 0x65, 0x6d, 0x10, 0x01, 0x2a, 0x3d, 0x0a, 0x06, 0x47, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x0a, 0x47, 0x4d, 0x54, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x47, 0x4d, 0x54, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x63,
	0x6b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x4d, 0x54, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f,
	0x63, 0x6b, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x6d, 0x73, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smsg_admin_msg_proto_rawDescOnce sync.Once
	file_smsg_admin_msg_proto_rawDescData = file_smsg_admin_msg_proto_rawDesc
)

func file_smsg_admin_msg_proto_rawDescGZIP() []byte {
	file_smsg_admin_msg_proto_rawDescOnce.Do(func() {
		file_smsg_admin_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_smsg_admin_msg_proto_rawDescData)
	})
	return file_smsg_admin_msg_proto_rawDescData
}

var file_smsg_admin_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_smsg_admin_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_smsg_admin_msg_proto_goTypes = []interface{}{
	(ChangeUserDataTyp)(0),                   // 0: smsg.ChangeUserDataTyp
	(GMType)(0),                              // 1: smsg.GMType
	(PuEnAddProp_OptType)(0),                 // 2: smsg.PuEnAddProp.OptType
	(PuEnRespAddProp_ErrCode)(0),             // 3: smsg.PuEnRespAddProp.ErrCode
	(PuEnRespBatchAddProp_ErrCode)(0),        // 4: smsg.PuEnRespBatchAddProp.ErrCode
	(AdEnRespChangeUserData_ErrCode)(0),      // 5: smsg.AdEnRespChangeUserData.ErrCode
	(AdAllRespReload_ErrCode)(0),             // 6: smsg.AdAllRespReload.ErrCode
	(AdAllRespCloseServer_ErrCode)(0),        // 7: smsg.AdAllRespCloseServer.ErrCode
	(AdAllRespGMCommand_ErrCode)(0),          // 8: smsg.AdAllRespGMCommand.ErrCode
	(AdAllRespMetrics_MetricsType)(0),        // 9: smsg.AdAllRespMetrics.MetricsType
	(AsAllReqMSGMonitor_Type)(0),             // 10: smsg.AsAllReqMSGMonitor.Type
	(AsAllRespMSGMonitor_ErrCode)(0),         // 11: smsg.AsAllRespMSGMonitor.ErrCode
	(*PuEnAddProp)(nil),                      // 12: smsg.PuEnAddProp
	(*PuEnRespAddProp)(nil),                  // 13: smsg.PuEnRespAddProp
	(*PuEnReqBatchAddProp)(nil),              // 14: smsg.PuEnReqBatchAddProp
	(*PuEnRespBatchAddProp)(nil),             // 15: smsg.PuEnRespBatchAddProp
	(*DelUserItem)(nil),                      // 16: smsg.DelUserItem
	(*ReqQueryBackup)(nil),                   // 17: smsg.ReqQueryBackup
	(*RespQueryBackup)(nil),                  // 18: smsg.RespQueryBackup
	(*AdEnReqChangeUserData)(nil),            // 19: smsg.AdEnReqChangeUserData
	(*AdEnRespChangeUserData)(nil),           // 20: smsg.AdEnRespChangeUserData
	(*AdAllReqReload)(nil),                   // 21: smsg.AdAllReqReload
	(*AdAllRespReload)(nil),                  // 22: smsg.AdAllRespReload
	(*AdAllReqCloseServer)(nil),              // 23: smsg.AdAllReqCloseServer
	(*AdAllRespCloseServer)(nil),             // 24: smsg.AdAllRespCloseServer
	(*AdAllReqGMCommand)(nil),                // 25: smsg.AdAllReqGMCommand
	(*AdAllRespGMCommand)(nil),               // 26: smsg.AdAllRespGMCommand
	(*AllGaNtfKickUserOut)(nil),              // 27: smsg.AllGaNtfKickUserOut
	(*AdAllReqMetrics)(nil),                  // 28: smsg.AdAllReqMetrics
	(*AdAllRespMetrics)(nil),                 // 29: smsg.AdAllRespMetrics
	(*AsAllReqMSGMonitor)(nil),               // 30: smsg.AsAllReqMSGMonitor
	(*AsAllRespMSGMonitor)(nil),              // 31: smsg.AsAllRespMSGMonitor
	(*PuEnReqBatchAddProp_Item)(nil),         // 32: smsg.PuEnReqBatchAddProp.Item
	(*AdAllReqGMCommand_Lock)(nil),           // 33: smsg.AdAllReqGMCommand.Lock
	(*AdAllRespGMCommand_Lock)(nil),          // 34: smsg.AdAllRespGMCommand.Lock
	(*AdAllRespMetrics_Metrics)(nil),         // 35: smsg.AdAllRespMetrics.Metrics
	(*AsAllRespMSGMonitor_RECReqResult)(nil), // 36: smsg.AsAllRespMSGMonitor.RECReqResult
	nil,                                      // 37: smsg.AsAllRespMSGMonitor.RECReqResult.MsgsEntry
	(*gameconf.PropPack)(nil),                // 38: gameconf.PropPack
	(gameconf.KickUserOutReason)(0),          // 39: gameconf.KickUserOutReason
}
var file_smsg_admin_msg_proto_depIdxs = []int32{
	2,  // 0: smsg.PuEnAddProp.optType:type_name -> smsg.PuEnAddProp.OptType
	38, // 1: smsg.PuEnAddProp.itemsAdd:type_name -> gameconf.PropPack
	38, // 2: smsg.PuEnAddProp.itemsSub:type_name -> gameconf.PropPack
	3,  // 3: smsg.PuEnRespAddProp.errCode:type_name -> smsg.PuEnRespAddProp.ErrCode
	38, // 4: smsg.PuEnRespAddProp.get:type_name -> gameconf.PropPack
	32, // 5: smsg.PuEnReqBatchAddProp.addList:type_name -> smsg.PuEnReqBatchAddProp.Item
	4,  // 6: smsg.PuEnRespBatchAddProp.errCode:type_name -> smsg.PuEnRespBatchAddProp.ErrCode
	38, // 7: smsg.PuEnRespBatchAddProp.get:type_name -> gameconf.PropPack
	0,  // 8: smsg.AdEnReqChangeUserData.type:type_name -> smsg.ChangeUserDataTyp
	16, // 9: smsg.AdEnReqChangeUserData.delUserItem:type_name -> smsg.DelUserItem
	5,  // 10: smsg.AdEnRespChangeUserData.errCode:type_name -> smsg.AdEnRespChangeUserData.ErrCode
	6,  // 11: smsg.AdAllRespReload.errCode:type_name -> smsg.AdAllRespReload.ErrCode
	7,  // 12: smsg.AdAllRespCloseServer.errCode:type_name -> smsg.AdAllRespCloseServer.ErrCode
	1,  // 13: smsg.AdAllReqGMCommand.gmtype:type_name -> smsg.GMType
	33, // 14: smsg.AdAllReqGMCommand.lock:type_name -> smsg.AdAllReqGMCommand.Lock
	8,  // 15: smsg.AdAllRespGMCommand.errCode:type_name -> smsg.AdAllRespGMCommand.ErrCode
	1,  // 16: smsg.AdAllRespGMCommand.gmtype:type_name -> smsg.GMType
	34, // 17: smsg.AdAllRespGMCommand.lock:type_name -> smsg.AdAllRespGMCommand.Lock
	39, // 18: smsg.AllGaNtfKickUserOut.reason:type_name -> gameconf.KickUserOutReason
	35, // 19: smsg.AdAllRespMetrics.metrics:type_name -> smsg.AdAllRespMetrics.Metrics
	10, // 20: smsg.AsAllReqMSGMonitor.type:type_name -> smsg.AsAllReqMSGMonitor.Type
	11, // 21: smsg.AsAllRespMSGMonitor.errCode:type_name -> smsg.AsAllRespMSGMonitor.ErrCode
	36, // 22: smsg.AsAllRespMSGMonitor.RECResult:type_name -> smsg.AsAllRespMSGMonitor.RECReqResult
	38, // 23: smsg.PuEnReqBatchAddProp.Item.itemsAdd:type_name -> gameconf.PropPack
	9,  // 24: smsg.AdAllRespMetrics.Metrics.key:type_name -> smsg.AdAllRespMetrics.MetricsType
	37, // 25: smsg.AsAllRespMSGMonitor.RECReqResult.msgs:type_name -> smsg.AsAllRespMSGMonitor.RECReqResult.MsgsEntry
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_smsg_admin_msg_proto_init() }
func file_smsg_admin_msg_proto_init() {
	if File_smsg_admin_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smsg_admin_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuEnAddProp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuEnRespAddProp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuEnReqBatchAddProp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuEnRespBatchAddProp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelUserItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryBackup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespQueryBackup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdEnReqChangeUserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdEnRespChangeUserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllReqReload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllRespReload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllReqCloseServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllRespCloseServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllReqGMCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllRespGMCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllGaNtfKickUserOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllReqMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllRespMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsAllReqMSGMonitor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsAllRespMSGMonitor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuEnReqBatchAddProp_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllReqGMCommand_Lock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllRespGMCommand_Lock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdAllRespMetrics_Metrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smsg_admin_msg_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsAllRespMSGMonitor_RECReqResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smsg_admin_msg_proto_rawDesc,
			NumEnums:      12,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smsg_admin_msg_proto_goTypes,
		DependencyIndexes: file_smsg_admin_msg_proto_depIdxs,
		EnumInfos:         file_smsg_admin_msg_proto_enumTypes,
		MessageInfos:      file_smsg_admin_msg_proto_msgTypes,
	}.Build()
	File_smsg_admin_msg_proto = out.File
	file_smsg_admin_msg_proto_rawDesc = nil
	file_smsg_admin_msg_proto_goTypes = nil
	file_smsg_admin_msg_proto_depIdxs = nil
}
